title: "Kieran McShane: Notes"
description: "Essays on quantum theory and related mathematics."
lang: en
author: Kieran McShane
url: "https://kieranmcshane.github.io"
baseurl: ""
theme: minima
markdown: kramdown
permalink: /:year/:month/:day/:title/
show_excerpts: true
header_pages:
  - about.md
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
